---
os_public_hostname: '{{ ansible_fqdn }}'
keystone_config_base:
  - { section: 'DEFAULT', option: 'admin_token', value: '{{ os_admin_token }}' }
  - { section: 'database', option: 'connection' , value: 'mysql+pymysql://keystone:{{ mysql_keystone_password }}@localhost/keystone' }
  - { section: 'memcache', option: 'servers' , value: 'localhost:11211' }
  - { section: 'token', option: 'provider' , value: 'uuid' }
  - { section: 'token', option: 'driver', value: 'memcache' }
  - { section: 'revoke', option: 'driver', value: 'sql' }

os_services:
  - { name: keystone, desc: 'OpenStack Identity', type: identity }
  - { name: glance, desc: 'OpenStack Image Service', type: image }
  - { name: nova, desc: 'OpenStack Compute Service', type: compute }
  - { name: cinder, desc: 'OpenStack Block Storage', type: volume }
  - { name: cinderv2, desc: 'OpenStack Block Storage', type: volumev2 }
  - { name: neutron, desc: 'OpenStack Networking', type: network }
  - { name: heat, desc: 'Orchestration', type: orchestration }
  - { name: heat-cfn, desc: 'Orchestration', type: cloudformation }
  - { name: murano, desc: 'Application Catalog for OpenStack', type: application_catalog }
  - { name: swift, desc: 'OpenStack Object Storage', type: object-store }

os_domains:
  - { name: heat , desc: 'Stack projects and users' }

os_endpoints:
  - name: keystone
    public: http://{{ os_public_hostname }}:5000/v2.0
    internal: http://{{ os_public_hostname }}:5000/v2.0
    admin: http://{{ os_public_hostname }}:35357/v2.0
    region: RegionOne
    type: identity
  - name: glance
    public: http://{{ os_public_hostname }}:9292
    internal: http://{{ os_public_hostname }}:9292
    admin: http://{{ os_public_hostname }}:9292
    region: RegionOne
    type: image
  - name: nova
    public: http://{{ os_public_hostname }}:8774/v2/%(tenant_id)s
    internal: http://{{ os_public_hostname }}:8774/v2/%(tenant_id)s
    admin: http://{{ os_public_hostname }}:8774/v2/%(tenant_id)s
    region: RegionOne
    type: compute
  - name: cinder
    public: http://{{ os_public_hostname }}:8776/v1/%(tenant_id)s
    internal: http://{{ os_public_hostname }}:8776/v1/%(tenant_id)s
    admin: http://{{ os_public_hostname }}:8776/v1/%(tenant_id)s
    region: RegionOne
    type: volume
  - name: cinderv2
    public: http://{{ os_public_hostname }}:8776/v2/%(tenant_id)s
    internal: http://{{ os_public_hostname }}:8776/v2/%(tenant_id)s
    admin: http://{{ os_public_hostname }}:8776/v2/%(tenant_id)s
    region: RegionOne
    type: volumev2
  - name: neutron
    public: http://{{ os_public_hostname }}:9696
    internal: http://{{ os_public_hostname }}:9696
    admin: http://{{ os_public_hostname }}:9696
    region: RegionOne
    type: network
  - name: heat
    public: http://{{ os_public_hostname }}:8004/v1/%(tenant_id)s
    internal: http://{{ os_public_hostname }}:8004/v1/%(tenant_id)s
    admin: http://{{ os_public_hostname }}:8004/v1/%(tenant_id)s
    region: RegionOne
    type: orchestration
  - name: heat-cfn
    public: http://{{ os_public_hostname }}:8000/v1
    internal: http://{{ os_public_hostname }}:8000/v1
    admin: http://{{ os_public_hostname }}:8000/v1
    region: RegionOne
    type: cloudformation
  - name: murano
    public: http://{{ os_public_hostname }}:8082
    internal: http://{{ os_public_hostname }}:8082
    admin: http://{{ os_public_hostname }}:8082
    region: RegionOne
    type: application_catalog
  - name: swift
    public: http://{{ os_public_hostname }}:8080/v1/AUTH_%(tenant_id)s
    internal: http://{{ os_public_hostname }}:8080/v1/AUTH_%(tenant_id)s
    admin: http://{{ os_public_hostname }}:8080/v1
    region: RegionOne
    type: object-store

os_projects:
  - { name: admin, desc: 'Admin Project', domain: Default }
  - { name: service, desc: 'Service Project', domain: Default }

os_roles:
  - { name: admin }
  - { name: heat_stack_owner }
  - { name: heat_stack_user }

os_role_assignments:
  - { role: admin, project: admin, user: admin }
  - { role: admin, project: service, user: glance }
  - { role: admin, project: service, user: nova }
  - { role: admin, project: service, user: cinder }
  - { role: admin, project: service, user: neutron }
  - { role: admin, project: service, user: murano }
  - { role: admin, project: service, user: heat }
  - { role: admin, project: service, user: heat_domain_admin }
  - { role: admin, project: service, user: swift }

os_users:
  admin:
    domain: Default
    project: admin
    password: "{{ os_admin_password }}"
  glance:
    domain: Default
    project: service
    password: "{{ vault_glance_password }}"
  nova:
    domain: Default
    project: service
    password: "{{ vault_nova_password }}"
  cinder:
    domain: Default
    project: service
    password: "{{ vault_cinder_password }}"
  neutron:
    domain: Default
    project: service
    password: "{{ vault_neutron_password }}"
  heat:
    domain: Default
    project: service
    password: "{{ vault_heat_password }}"
  heat_domain_admin:
    domain: heat
    project: service
    password: "{{ vault_heat_domain_admin_password }}"
  murano:
    domain: Default
    project: service
    password: "{{ vault_murano_password }}"
  swift:
    domain: Default
    project: service
    password: "{{ vault_swift_password }}"
