---
keystone_config_base:
  - { section: 'DEFAULT', option: 'admin_token', value: '{{ os_admin_token }}' }
  - { section: 'database', option: 'connection' , value: 'mysql+pymysql://keystone:{{ mysql_keystone_password }}@{{ controller_mgmt_fqdn }}/keystone' }
  - { section: 'memcache', option: 'servers' , value: '{{ controller_mgmt_fqdn }}:11211' }
  - { section: 'token', option: 'provider' , value: 'uuid' }
  - { section: 'token', option: 'driver', value: 'memcache' }
  - { section: 'revoke', option: 'driver', value: 'sql' }

os_services:
  - { name: keystone, desc: 'OpenStack Identity', type: identity }
  - { name: glance, desc: 'OpenStack Image Service', type: image }
  - { name: nova, desc: 'OpenStack Compute Service', type: compute }
  - { name: cinder, desc: 'OpenStack Block Storage', type: volume }
  - { name: cinderv2, desc: 'OpenStack Block Storage', type: volumev2 }
  - { name: neutron, desc: 'OpenStack Networking', type: network }
  - { name: heat, desc: 'Orchestration', type: orchestration }
  - { name: heat-cfn, desc: 'Orchestration', type: cloudformation }
  - { name: murano, desc: 'Application Catalog for OpenStack', type: application_catalog }
  - { name: swift, desc: 'OpenStack Object Storage', type: object-store }
  - { name: ceilometer, desc: 'Telemetry', type: metering }

os_domains:
  - { name: heat , desc: 'Stack projects and users' }

os_endpoints:
  - name: keystone
    public: http://{{ controller_public_fqdn }}:5000/v2.0
    internal: http://{{ controller_mgmt_fqdn }}:5000/v2.0
    admin: http://{{ controller_mgmt_fqdn }}:35357/v2.0
    region: RegionOne
    type: identity
  - name: glance
    public: http://{{ controller_public_fqdn }}:9292
    internal: http://{{ controller_mgmt_fqdn }}:9292
    admin: http://{{ controller_mgmt_fqdn }}:9292
    region: RegionOne
    type: image
  - name: nova
    public: http://{{ controller_public_fqdn }}:8774/v2/%(tenant_id)s
    internal: http://{{ controller_mgmt_fqdn }}:8774/v2/%(tenant_id)s
    admin: http://{{ controller_mgmt_fqdn }}:8774/v2/%(tenant_id)s
    region: RegionOne
    type: compute
  - name: cinder
    public: http://{{ controller_public_fqdn }}:8776/v1/%(tenant_id)s
    internal: http://{{ controller_mgmt_fqdn }}:8776/v1/%(tenant_id)s
    admin: http://{{ controller_mgmt_fqdn }}:8776/v1/%(tenant_id)s
    region: RegionOne
    type: volume
  - name: cinderv2
    public: http://{{ controller_public_fqdn }}:8776/v2/%(tenant_id)s
    internal: http://{{ controller_mgmt_fqdn }}:8776/v2/%(tenant_id)s
    admin: http://{{ controller_mgmt_fqdn }}:8776/v2/%(tenant_id)s
    region: RegionOne
    type: volumev2
  - name: neutron
    public: http://{{ controller_public_fqdn }}:9696
    internal: http://{{ controller_mgmt_fqdn }}:9696
    admin: http://{{ controller_mgmt_fqdn }}:9696
    region: RegionOne
    type: network
  - name: heat
    public: http://{{ controller_public_fqdn }}:8004/v1/%(tenant_id)s
    internal: http://{{ controller_mgmt_fqdn }}:8004/v1/%(tenant_id)s
    admin: http://{{ controller_mgmt_fqdn }}:8004/v1/%(tenant_id)s
    region: RegionOne
    type: orchestration
  - name: heat-cfn
    public: http://{{ controller_public_fqdn }}:8000/v1
    internal: http://{{ controller_mgmt_fqdn }}:8000/v1
    admin: http://{{ controller_mgmt_fqdn }}:8000/v1
    region: RegionOne
    type: cloudformation
  - name: murano
    public: http://{{ controller_public_fqdn }}:8082
    internal: http://{{ controller_mgmt_fqdn }}:8082
    admin: http://{{ controller_mgmt_fqdn }}:8082
    region: RegionOne
    type: application_catalog
  - name: swift
    public: http://{{ controller_public_fqdn }}:8080/v1/AUTH_%(tenant_id)s
    internal: http://{{ controller_mgmt_fqdn }}:8080/v1/AUTH_%(tenant_id)s
    admin: http://{{ controller_mgmt_fqdn }}:8080/v1
    region: RegionOne
    type: object-store
  - name: ceilometer
    public: http://{{ controller_public_fqdn }}:8777
    internal: http://{{ controller_mgmt_fqdn }}:8777
    admin: http://{{ controller_mgmt_fqdn }}:8777
    region: RegionOne
    type: metering

os_projects:
  - { name: admin, desc: 'Admin Project', domain: Default }
  - { name: service, desc: 'Service Project', domain: Default }

os_roles:
  - { name: admin }
  - { name: heat_stack_owner }
  - { name: heat_stack_user }
  - { name: ResellerAdmin }

os_role_assignments:
  - { role: admin, project: admin, user: admin }
  - { role: admin, project: service, user: glance }
  - { role: admin, project: service, user: nova }
  - { role: admin, project: service, user: cinder }
  - { role: admin, project: service, user: neutron }
  - { role: admin, project: service, user: murano }
  - { role: admin, project: service, user: heat }
  - { role: admin, project: service, user: swift }
  - { role: admin, project: service, user: ceilometer }
  - { role: ResellerAdmin, project: service, user: ceilometer }
