---
- name: neutron db_sync
  command: neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head
  become_user: neutron

- name: neutron db_sync lbaas
  command: neutron-db-manage --service lbaas upgrade head
  become_user: neutron

- name: restart neutron-server
  service:
    name: neutron-server
    state: restarted

- name: restart neutron-plugin-openvswitch-agent
  service:
    name: neutron-plugin-openvswitch-agent
    state: restarted

- name: restart neutron-dhcp-agent
  service:
    name: neutron-dhcp-agent
    state: restarted

- name: restart neutron-metadata-agent
  service:
    name: neutron-metadata-agent
    state: restarted

- name: restart neutron-l3-agent
  service:
    name: neutron-l3-agent
    state: restarted

- name: restart neutron-metering-agent
  service:
    name: neutron-metering-agent
    state: restarted

- name: restart neutron-lbaasv2-agent
  service:
    name: neutron-lbaasv2-agent
    state: restarted

- name: apply sysctl settings
  command: sysctl -p
