---
mysql_root_password: '{{ vault_mysql_root_password }}'
mysql_keystone_password: '{{ vault_mysql_keystone_password }}'
mysql_glance_password: '{{ vault_mysql_glance_password }}'
mysql_nova_password: '{{ vault_mysql_nova_password }}'
mysql_cinder_password: '{{ vault_mysql_cinder_password }}'
mysql_neutron_password: '{{ vault_mysql_neutron_password }}'
mysql_heat_password: '{{ vault_mysql_heat_password }}'
mysql_murano_password: '{{ vault_mysql_murano_password }}'
rabbitmq_openstack_password: '{{ vault_rabbitmq_openstack_password }}'
metadata_proxy_shared_secret: '{{ vault_metadata_proxy_shared_secret }}'
swift_hash_path_suffix: '{{ vault_swift_hash_path_suffix }}'
swift_hash_path_prefix: '{{ vault_swift_hash_path_prefix }}'

os_mgmt_iface: mgmt0
os_storage_iface: mgmt0
os_tunnel_iface: tunnel0
os_public_iface: br-ext

controller_mgmt_ip: 192.168.99.2
controller_mgmt_fqdn: controller.os_mgmt.local
controller_mgmt_hostname: stack.chaosmoon.net

os_users:
  admin:
    domain: Default
    project: admin
    password: "{{ os_admin_password }}"
  glance:
    domain: Default
    project: service
    password: "{{ vault_glance_password }}"
  nova:
    domain: Default
    project: service
    password: "{{ vault_nova_password }}"
  cinder:
    domain: Default
    project: service
    password: "{{ vault_cinder_password }}"
  neutron:
    domain: Default
    project: service
    password: "{{ vault_neutron_password }}"
  heat:
    domain: Default
    project: service
    password: "{{ vault_heat_password }}"
  heat_domain_admin:
    domain: heat
    project: service
    password: "{{ vault_heat_domain_admin_password }}"
  murano:
    domain: Default
    project: service
    password: "{{ vault_murano_password }}"
  swift:
    domain: Default
    project: service
    password: "{{ vault_swift_password }}"
