---
- name: reboot machine
  shell: sleep 2 && shutdown -r now "Reboot after deploy"
  async: 1
  poll: 0
  ignore_errors: true
  when: do_reboot|default(false)

- name: waiting for server to come back
  local_action: wait_for 
  args:
    port: 22
    host: "{{ ansible_host | default(inventory_hostname) }}"
    search_regex: OpenSSH
    delay: 60
  become: false
  when: do_reboot|default(false)
