---
os_public_hostname: '{{ ansible_fqdn }}'
nova_compute_config_base:
  - { section: 'DEFAULT', option: 'rpc_backend', value: 'rabbit' }
  - { section: 'oslo_messaging_rabbit', option: 'rabbit_host', value: '{{ os_public_hostname }}' }
  - { section: 'oslo_messaging_rabbit', option: 'rabbit_userid', value: 'openstack' }
  - { section: 'oslo_messaging_rabbit', option: 'rabbit_password', value: '{{ rabbitmq_openstack_password }}' }
  - { section: 'DEFAULT', option: 'auth_strategy', value: 'keystone' }
  - { section: 'keystone_authtoken', option: 'auth_uri', value: 'http://{{ os_public_hostname }}:5000' }
  - { section: 'keystone_authtoken', option: 'auth_url', value: 'http://{{ os_public_hostname }}:35357' }
  - { section: 'keystone_authtoken', option: 'auth_plugin', value: 'password' }
  - { section: 'keystone_authtoken', option: 'project_domain_id', value: 'default' }
  - { section: 'keystone_authtoken', option: 'user_domain_id', value: 'default' }
  - { section: 'keystone_authtoken', option: 'project_name', value: 'service' }
  - { section: 'keystone_authtoken', option: 'username', value: 'nova' }
  - { section: 'keystone_authtoken', option: 'password', value: '{{ os_users.nova.password }}' }
  - { section: 'DEFAULT', option: 'network_api_class' , value: 'nova.network.neutronv2.api.API' }
  - { section: 'DEFAULT', option: 'security_group_api' , value: 'neutron' }
  - { section: 'DEFAULT', option: 'linuxnet_interface_driver' , value: 'nova.network.linux_net.NeutronLinuxBridgeInterfaceDriver' }
  - { section: 'DEFAULT', option: 'firewall_driver' , value: 'nova.virt.firewall.NoopFirewallDriver' }
  - { section: 'DEFAULT', option: 'my_ip' , value: '{{ ansible_default_ipv4.address }}' }
  - { section: 'vnc', option: 'enabled' , value: 'True' }
  - { section: 'vnc', option: 'vncserver_listen' , value: '0.0.0.0' }
  - { section: 'vnc', option: 'vncserver_proxyclient_address' , value: '$my_ip' }
  - { section: 'vnc', option: 'novncproxy_base_url' , value: 'http://{{ os_public_hostname }}:6080/vnc_auto.html' }
  - { section: 'glance', option: 'host' , value: '{{ os_public_hostname }}' }
  - { section: 'oslo_concurrency', option: 'lock_path' , value: '/var/lib/nova/tmp' }
