---
- name: install neutron legacy openvswitch components
  apt:
    state: present
    name: '{{ item }}'
  with_items:
    - neutron-plugin-ml2
    - neutron-plugin-openvswitch-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-metering-agent
    - neutron-lbaasv2-agent

- name: neutron ml2 base configuration
  ini_file:
    dest: /etc/neutron/neutron.conf
    owner: root
    group: root
    mode: 0644
    section: '{{ item.section }}'
    option: '{{ item.option|default(omit) }}'
    value: '{{ item.value|default(omit) }}'
  no_log: true
  with_items:
    - '{{ neutron_ml2_config_base + neutron_ml2_config|default([]) }}'
  notify:
    - neutron db_sync
    - restart neutron-server

- name: ml2 plugin base configuration
  ini_file:
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini 
    owner: root
    group: root
    mode: 0644
    section: '{{ item.section }}'
    option: '{{ item.option|default(omit) }}'
    value: '{{ item.value|default(omit) }}'
  no_log: true
  with_items:
    - '{{ ml2_plugin_config_base + ml2_plugin_config|default([]) }}'
  notify:
    - neutron db_sync
    - restart neutron-server

- name: ml2 openvswitch agent base configuration
  ini_file:
    dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    owner: root
    group: root
    mode: 0644
    section: '{{ item.section }}'
    option: '{{ item.option|default(omit) }}'
    value: '{{ item.value|default(omit) }}'
  no_log: true
  with_items:
    - '{{ ml2_ovs_config_base + ml2_ovs_config|default([]) }}'
  notify:
    - restart neutron-plugin-openvswitch-agent

- name: neutron layer 3 agent base configuration
  ini_file:
    dest: /etc/neutron/l3_agent.ini
    owner: root
    group: root
    mode: 0644
    section: '{{ item.section }}'
    option: '{{ item.option|default(omit) }}'
    value: '{{ item.value|default(omit) }}'
  no_log: true
  with_items:
    - '{{ neutron_layer3_config_base + neutron_layer3_config|default([]) }}'
  notify:
    - restart neutron-l3-agent

- name: neutron dhcp agent base configuration
  ini_file:
    dest: /etc/neutron/dhcp_agent.ini
    owner: root
    group: root
    mode: 0644
    section: '{{ item.section }}'
    option: '{{ item.option|default(omit) }}'
    value: '{{ item.value|default(omit) }}'
  no_log: true
  with_items:
    - '{{ neutron_dhcp_config_base + neutron_dhcp_config|default([]) }}'
  notify:
    - restart neutron-dhcp-agent

- name: neutron dnsmasq base configuration
  lineinfile:
    dest: /etc/neutron/dnsmasq-neutron.conf
    owner: root
    group: root
    mode: 0644
    create: true
    regexp: ^{{ item.option }}\s*=.*$
    line: '{{ item.option }}={{ item.value }}'
  with_items:
    - '{{ neutron_dnsmasq_config_base + neutron_dnsmasq_config|default([]) }}'
  notify:
    - restart neutron-dhcp-agent

- name: neutron metadata agent base configuration
  ini_file:
    dest: /etc/neutron/metadata_agent.ini
    owner: root
    group: root
    mode: 0644
    section: '{{ item.section }}'
    option: '{{ item.option|default(omit) }}'
    value: '{{ item.value|default(omit) }}'
  no_log: true
  with_items:
    - '{{ neutron_metadata_config_base + neutron_metadata_config|default([]) }}'
  notify:
    - restart neutron-metadata-agent

- name: neutron metering agent base configuration
  ini_file:
    dest: /etc/neutron/metering_agent.ini
    owner: root
    group: root
    mode: 0644
    section: '{{ item.section }}'
    option: '{{ item.option|default(omit) }}'
    value: '{{ item.value|default(omit) }}'
  no_log: true
  with_items:
    - '{{ neutron_metering_config_base + neutron_metering_config|default([]) }}'
  notify:
    - restart neutron-metering-agent

- name: neutron lbaas agent base configuration
  ini_file:
    dest: /etc/neutron/lbaas_agent.ini
    owner: root
    group: root
    mode: 0644
    section: '{{ item.section }}'
    option: '{{ item.option|default(omit) }}'
    value: '{{ item.value|default(omit) }}'
  no_log: true
  with_items:
    - '{{ neutron_lbaas_agent_config_base + neutron_lbaas_agent_config|default([]) }}'
  notify:
    - restart neutron-lbaasv2-agent
    - neutron db_sync lbaas

- name: neutron lbaasv2 base configuration
  ini_file:
    dest: /etc/neutron/neutron_lbaas.conf
    owner: root
    group: root
    mode: 0644
    section: '{{ item.section }}'
    option: '{{ item.option|default(omit) }}'
    value: '{{ item.value|default(omit) }}'
  no_log: true
  with_items:
    - '{{ neutron_lbaasv2_config_base + neutron_lbaasv2_config|default([]) }}'
  notify:
    - restart neutron-lbaasv2-agent
    - neutron db_sync lbaas

- name: add sysctl settings for ovs compute
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: ^#*\s*{{ item.option }}\s*=.*
    line: '{{ item.option }}={{ item.value }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - '{{ ml2_ovs_compute_sysctl_config_base + ml2_ovs_compute_sysctl_config|default([]) }}'
  notify: apply sysctl settings

- meta: flush_handlers

# TODO: refactoring necessary
- name: enable / start neutron-plugin-openvswitch-agent service
  service:
    name: neutron-plugin-openvswitch-agent
    enabled: '{{ neutron_plugin_openvswitch_agent_enabled | default("yes") }}'
    state: '{{ neutron_plugin_openvswitch_agent_state | default("started") }}'

- name: enable / start neutron-dhcp-agent service
  service:
    name: neutron-dhcp-agent
    enabled: '{{ neutron_dhcp_agent_enabled | default("yes") }}'
    state: '{{ neutron_dhcp_agent_state | default("started") }}'

- name: enable / start neutron-metadata-agent service
  service:
    name: neutron-metadata-agent
    enabled: '{{ neutron_metadata_agent_enabled | default("yes") }}'
    state: '{{ neutron_metadata_agent_state | default("started") }}'

- name: enable / start neutron-l3-agent service
  service:
    name: neutron-l3-agent
    enabled: '{{ neutron_l3_agent_enabled | default("yes") }}'
    state: '{{ neutron_al3_agent_state | default("started") }}'

- name: enable / start neutron-metering-agent service
  service:
    name: neutron-metering-agent
    enabled: '{{ neutron_metering_agent_enabled | default("yes") }}'
    state: '{{ neutron_metering_agent_state | default("started") }}'

- name: enable / start neutron-lbaasv2-agent service
  service:
    name: neutron-lbaasv2-agent
    enabled: '{{ neutron_lbaasv2_agent_enabled | default("yes") }}'
    state: '{{ neutron_lbaasv2_agent_state | default("started") }}'
