---
- name: install neutron legacy bridge components
  apt:
    state: present
    name: '{{ item }}'
  with_items:
    - neutron-plugin-ml2
    - neutron-plugin-linuxbridge-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent

- name: neutron ml2 base configuration
  ini_file:
    dest: /etc/neutron/neutron.conf
    owner: root
    group: root
    mode: 0644
    section: '{{ item.section }}'
    option: '{{ item.option|default(omit) }}'
    value: '{{ item.value|default(omit) }}'
  no_log: true
  with_items:
    - '{{ neutron_ml2_config_base + neutron_ml2_config|default([]) }}'
  notify:
    - neutron db_sync
    - restart neutron-server

- name: ml2 plugin base configuration
  ini_file:
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini 
    owner: root
    group: root
    mode: 0644
    section: '{{ item.section }}'
    option: '{{ item.option|default(omit) }}'
    value: '{{ item.value|default(omit) }}'
  no_log: true
  with_items:
    - '{{ ml2_plugin_config_base + ml2_plugin_config|default([]) }}'
  notify:
    - neutron db_sync
    - restart neutron-server

- name: ml2 bridge agent base configuration
  ini_file:
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini 
    owner: root
    group: root
    mode: 0644
    section: '{{ item.section }}'
    option: '{{ item.option|default(omit) }}'
    value: '{{ item.value|default(omit) }}'
  no_log: true
  with_items:
    - '{{ ml2_bridge_config_base + ml2_bridge_config|default([]) }}'
  notify:
    - restart neutron-plugin-linuxbridge-agent

- name: neutron layer 3 agent base configuration
  ini_file:
    dest: /etc/neutron/l3_agent.ini
    owner: root
    group: root
    mode: 0644
    section: '{{ item.section }}'
    option: '{{ item.option|default(omit) }}'
    value: '{{ item.value|default(omit) }}'
  no_log: true
  with_items:
    - '{{ neutron_layer3_config_base + neutron_layer3_config|default([]) }}'
  notify:
    - restart neutron-l3-agent

- name: neutron dhcp agent base configuration
  ini_file:
    dest: /etc/neutron/l3_agent.ini
    owner: root
    group: root
    mode: 0644
    section: '{{ item.section }}'
    option: '{{ item.option|default(omit) }}'
    value: '{{ item.value|default(omit) }}'
  no_log: true
  with_items:
    - '{{ neutron_dhcp_config_base + neutron_dhcp_config|default([]) }}'
  notify:
    - restart neutron-dhcp-agent

- name: neutron dnsmasq base configuration
  lineinfile:
    dest: /etc/neutron/dnsmasq-neutron.conf
    owner: root
    group: root
    mode: 0644
    regexp: ^{{ item.option }}\s*=.*$
    line: '{{ item.option }}={{ item.value }}'
  with_items:
    - '{{ neutron_dnsmasq_config_base + neutron_dnsmasq_config|default([]) }}'
  notify:
    - restart neutron-dhcp-agent

- name: neutron metadata agent base configuration
  ini_file:
    dest: /etc/neutron/metadata_agent.ini
    owner: root
    group: root
    mode: 0644
    section: '{{ item.section }}'
    option: '{{ item.option|default(omit) }}'
    value: '{{ item.value|default(omit) }}'
  no_log: true
  with_items:
    - '{{ neutron_metadata_config_base + neutron_metadata_config|default([]) }}'
  notify:
    - restart neutron-metadata-agent

- meta: flush_handlers

# TODO: refactoring necessary
- name: enable / start neutron-plugin-linuxbridge-agent service
  service:
    name: neutron-plugin-linuxbridge-agent
    enabled: '{{ neutron_plugin_linuxbridge_agent_enabled | default("yes") }}'
    state: '{{ neutron_plugin_linuxbridge_agent_state | default("started") }}'

- name: enable / start neutron-dhcp-agent service
  service:
    name: neutron-dhcp-agent
    enabled: '{{ neutron_dhcp_agent_enabled | default("yes") }}'
    state: '{{ neutron_dhcp_agent_state | default("started") }}'

- name: enable / start neutron-metadata-agent service
  service:
    name: neutron-metadata-agent
    enabled: '{{ neutron_metadata_agent_enabled | default("yes") }}'
    state: '{{ neutron_metadata_agent_state | default("started") }}'

- name: enable / start neutron-l3-agent service
  service:
    name: neutron-l3-agent
    enabled: '{{ neutron_l3_agent_enabled | default("yes") }}'
    state: '{{ neutron_al3_agent_state | default("started") }}'
