---
ml2_ovs_compute_config_base:
  - { section: 'ovs', option: 'local_ip', value: '{{ os_tunnel_ip }}' }
  - { section: 'ovs', option: 'enable_tunneling', value: 'True' }
  - { section: 'ovs', option: 'bridge_mappings', value: 'public:{{ os_public_iface }}' }
  - { section: 'agent', option: 'prevent_arp_spoofing', value: 'True' }
  - { section: 'agent', option: 'tunnel_types', value: 'vxlan' }
  - { section: 'agent', option: 'l2_population', value: 'True' }
  - { section: 'securitygroup', option: 'enable_security_group', value: 'True' }
  - { section: 'securitygroup', option: 'enable_ipset', value: 'True' }
  - { section: 'securitygroup', option: 'firewall_driver', value: 'neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver' }
ml2_ovs_compute_sysctl_config_base:
  - { option: 'net.ipv4.conf.default.rp_filter',value: '0'}
  - { option: 'net.ipv4.conf.all.rp_filter',value: '0'}
  - { option: 'net.bridge.bridge-nf-call-iptables',value: '1'}
  - { option: 'net.bridge.bridge-nf-call-ip6tables',value: '1'}
