---
- name: install neutron legacy bridge compute components
  apt:
    state: present
    name: '{{ item }}'
  with_items:
    - neutron-plugin-linuxbridge-agent

- name: ml2 bridge agent base configuration
  ini_file:
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    owner: root
    group: root
    mode: 0644
    section: '{{ item.section }}'
    option: '{{ item.option|default(omit) }}'
    value: '{{ item.value|default(omit) }}'
  no_log: true
  with_items:
    - '{{ ml2_bridge_compute_config_base + ml2_bridge_compute_config|default([]) }}'
  notify:
    - restart neutron-plugin-linuxbridge-agent
