---
- name: install neutron compute components
  apt:
    state: present
    name: '{{ item }}'
  with_items:
    - neutron-common

- name: neutron base configuration
  ini_file:
    dest: /etc/neutron/neutron.conf
    owner: root
    group: root
    mode: 0644
    section: '{{ item.section }}'
    option: '{{ item.option|default(omit) }}'
    value: '{{ item.value|default(omit) }}'
  no_log: true
  with_items:
    - '{{ neutron_compute_config_base + neutron_compute_config|default([]) }}'

- name: load br_netfilter on system start
  lineinfile:
    dest: /etc/modules
    line: br_netfilter
    owner: root
    group: root
    mode: 0644

- name: load br_netfilter module
  command: modprobe br_netfilter
