---
neutron_control_config_base:
  - { section: 'database', option: 'connection' , value: 'mysql+pymysql://neutron:{{ mysql_neutron_password }}@{{ controller_mgmt_fqdn }}/neutron' }
  - { section: 'DEFAULT', option: 'rpc_backend', value: 'rabbit' }
  - { section: 'oslo_messaging_rabbit', option: 'rabbit_host', value: '{{ controller_mgmt_fqdn }}' }
  - { section: 'oslo_messaging_rabbit', option: 'rabbit_userid', value: 'openstack' }
  - { section: 'oslo_messaging_rabbit', option: 'rabbit_password', value: '{{ rabbitmq_openstack_password }}' }
  - { section: 'DEFAULT', option: 'auth_strategy', value: 'keystone' }
  - { section: 'keystone_authtoken', option: 'auth_uri', value: 'http://{{ controller_mgmt_fqdn }}:5000' }
  - { section: 'keystone_authtoken', option: 'auth_url', value: 'http://{{ controller_mgmt_fqdn }}:35357' }
  - { section: 'keystone_authtoken', option: 'auth_plugin', value: 'password' }
  - { section: 'keystone_authtoken', option: 'project_domain_id', value: 'default' }
  - { section: 'keystone_authtoken', option: 'user_domain_id', value: 'default' }
  - { section: 'keystone_authtoken', option: 'project_name', value: 'service' }
  - { section: 'keystone_authtoken', option: 'username', value: 'neutron' }
  - { section: 'keystone_authtoken', option: 'password', value: '{{ os_users.neutron.password }}' }
  - { section: 'DEFAULT', option: 'notify_nova_on_port_status_changes', value: 'True' }
  - { section: 'DEFAULT', option: 'notify_nova_on_port_data_changes', value: 'True' }
  - { section: 'DEFAULT', option: 'nova_url', value: 'http://{{ controller_mgmt_fqdn }}:8774/v2' }
  - { section: 'nova', option: 'auth_url', value: 'http://{{ controller_mgmt_fqdn }}:35357' }
  - { section: 'nova', option: 'auth_plugin', value: 'password' }
  - { section: 'nova', option: 'project_domain_id', value: 'default' }
  - { section: 'nova', option: 'user_domain_id', value: 'default' }
  - { section: 'nova', option: 'region_name', value: 'RegionOne' }
  - { section: 'nova', option: 'project_name', value: 'service' }
  - { section: 'nova', option: 'username', value: 'nova' }
  - { section: 'nova', option: 'password', value: '{{ os_users.nova.password }}' }
