---
neutron_ml2_config_base:
  - { section: 'DEFAULT', option: 'core_plugin', value: 'ml2' }
  - { section: 'DEFAULT', option: 'service_plugins', value: 'router,metering,neutron_lbaas.services.loadbalancer.plugin.LoadBalancerPluginv2' }
  - { section: 'DEFAULT', option: 'allow_overlapping_ips', value: 'True' }
ml2_plugin_config_base:
  - { section: 'ml2', option: 'type_drivers', value: 'flat,vxlan' }
  - { section: 'ml2', option: 'tenant_network_types', value: 'vxlan' }
  - { section: 'ml2', option: 'mechanism_drivers', value: 'openvswitch,l2population' }
  - { section: 'ml2', option: 'extension_drivers', value: 'port_security' }
  - { section: 'ml2_type_flat', option: 'flat_networks', value: 'public' }
  - { section: 'ml2_type_vxlan', option: 'vni_ranges', value: '1:1000' }
  - { section: 'securitygroup', option: 'enable_ipset', value: 'True' }
  - { section: 'securitygroup', option: 'enable_security_group', value: 'True' }
  - { section: 'securitygroup', option: 'firewall_driver', value: 'neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver' }
ml2_ovs_config_base:
  - { section: 'ovs', option: 'local_ip', value: '{{ os_tunnel_ip }}' }
  - { section: 'ovs', option: 'enable_tunneling', value: 'True' }
  - { section: 'ovs', option: 'bridge_mappings', value: 'public:{{ os_public_iface }}' }
  - { section: 'agent', option: 'prevent_arp_spoofing', value: 'True' }
  - { section: 'agent', option: 'tunnel_types', value: 'vxlan' }
  - { section: 'agent', option: 'l2_population', value: 'True' }
  - { section: 'securitygroup', option: 'enable_security_group', value: 'True' }
  - { section: 'securitygroup', option: 'enable_ipset', value: 'True' }
  - { section: 'securitygroup', option: 'firewall_driver', value: 'neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver' }
neutron_layer3_config_base:
  - { section: 'DEFAULT', option: 'interface_driver', value: 'neutron.agent.linux.interface.OVSInterfaceDriver' }
  - { section: 'DEFAULT', option: 'use_namespaces', value: 'True' }
  - { section: 'DEFAULT', option: 'router_delete_namespaces', value: 'True' }
  - { section: 'DEFAULT', option: 'external_network_bridge', value: '' }
neutron_dhcp_config_base:
  - { section: 'DEFAULT', option: 'interface_driver', value: 'neutron.agent.linux.interface.OVSInterfaceDriver' }
  - { section: 'DEFAULT', option: 'dhcp_driver', value: 'neutron.agent.linux.dhcp.Dnsmasq' }
  - { section: 'DEFAULT', option: 'use_namespaces', value: 'True' }
  - { section: 'DEFAULT', option: 'dhcp_delete_namespaces', value: 'True' }
  - { section: 'DEFAULT', option: 'enable_isolated_metadata', value: 'True' }
  - { section: 'DEFAULT', option: 'dnsmasq_config_file', value: '/etc/neutron/dnsmasq-neutron.conf' }
neutron_metadata_config_base:
  - { section: 'DEFAULT', option: 'auth_uri', value: 'http://{{ controller_mgmt_fqdn }}:5000' }
  - { section: 'DEFAULT', option: 'auth_url', value: 'http://{{ controller_mgmt_fqdn }}:35357' }
  - { section: 'DEFAULT', option: 'auth_plugin', value: 'password' }
  - { section: 'DEFAULT', option: 'auth_region', value: 'RegionOne' }
  - { section: 'DEFAULT', option: 'project_domain_id', value: 'default' }
  - { section: 'DEFAULT', option: 'user_domain_id', value: 'default' }
  - { section: 'DEFAULT', option: 'project_name', value: 'service' }
  - { section: 'DEFAULT', option: 'username', value: 'neutron' }
  - { section: 'DEFAULT', option: 'password', value: '{{ os_users.neutron.password }}' }
  - { section: 'DEFAULT', option: 'nova_metadata_ip', value: '{{ controller_mgmt_fqdn }}' }
  - { section: 'DEFAULT', option: 'metadata_proxy_shared_secret', value: '{{ metadata_proxy_shared_secret }}' }
neutron_metering_config_base:
  - { section: 'DEFAULT', option: 'driver', value: 'neutron.services.metering.drivers.iptables.iptables_driver.IptablesMeteringDriver' }
  - { section: 'DEFAULT', option: 'interface_driver', value: 'neutron.agent.linux.interface.OVSInterfaceDriver' }
neutron_lbaas_agent_config_base:
  - { section: 'DEFAULT', option: 'interface_driver', value: 'neutron.agent.linux.interface.OVSInterfaceDriver' }
neutron_lbaasv2_config_base:
  - { section: 'service_providers', option: 'service_provider', value: 'LOADBALANCERV2:Haproxy:neutron_lbaas.drivers.haproxy.plugin_driver.HaproxyOnHostPluginDriver:default' }
neutron_dnsmasq_config_base:
  - { option: 'dhcp-option-force', value: '26,1452' }
ml2_ovs_compute_sysctl_config_base:
  - { option: 'net.ipv4.conf.default.rp_filter',value: '0'}
  - { option: 'net.ipv4.conf.all.rp_filter',value: '0'}
  - { option: 'net.ipv4.ip_forward',value: '1'}
