---
- name: base setup
  hosts: stack-nodes
  become: yes
  tags:
    - common

  roles:
    - role: base
      tags: ['base']
    - role: repositories
      tags: ['repositories']
    - role: firewall
      tags: ['firewall']


- name: set up controller node (phase 1)
  hosts: controller-nodes
  gather_facts: no
  become: yes
  tags:
    - controller

  roles:
    - role: memcached
      tags: ['memcached']
    - role: mariadb
      tags: ['mariadb']
    - role: rabbitmq
      tags: ['rabbitmq']
    - role: mongodb
      tags: ['mongodb']
    - role: os_common
      tags: ['os_common']
    - role: keystone
      tags: ['keystone']
    - role: cinder-controller
      tags: ['cinder','cinder-controller']

- name: set up storage nodes
  hosts: storage-nodes
  gather_facts: no
  become: yes
  tags:
    - storage

  pre_tasks:
    - name: create partitions
      command: parted -s {{ item }} mklabel gpt mkpart primary 2048s {{ cinder_size }} mkpart primary {{ cinder_size }} 100%
      args:
        creates: '{{ item }}1'
      with_items:
        - '{{ disks }}'

    - name: create software raid
      command: mdadm --create {{ raid1_dest_device }} -e 1.2 --level=1 --raid-devices={{ raid1_src_devices|length }} {{ raid1_src_devices|join(' ') }}
      args:
        creates: '{{ raid1_dest_device }}'

  roles:
    - role: cinder-storage
      tags: ['cinder','cinder-storage']
    - role: cinder-lvm
      tags: ['cinder','cinder-lvm']
    - role: swift-fs
      tags: ['swift','swift-fs']
    - role: swift-storage
      tags: ['swift','swift-storage']

- name: set up controller node (phase 2)
  hosts: controller-nodes
  gather_facts: no
  become: yes
  tags:
    - controller

  roles:
    - role: swift-controller
      tags: ['swift','swift-controller']
    - role: glance
      tags: ['glance']
    - role: glance-swift
      tags: ['glance','glance-swift']
    - role: reboot
      tags: ['reboot']

# vim: ft=ansible
