---
- name: "TODO: fix ring-builder.sh multi node support"
  fail:
  when: groups['storage-nodes']|length > 1

- block:
  - name: create builder files
    command: swift-ring-builder /etc/swift/{{ item }} create {{ swift_partition_exponent }} {{ swift_replicas }} {{ swift_rebalance_limit }}
    args:
      creates: /etc/swift/{{ item }}
    with_items:
      - account.builder
      - container.builder
      - object.builder

  - name: create ring-builder script
    template:
      src: ring-builder.sh.j2
      dest: /usr/local/sbin/ring-builder.sh
      owner: root
      group: root
      mode: 0754

  - name: create swift rings
    command: /usr/local/sbin/ring-builder.sh
    args:
      creates: /etc/swift/.rings_build

  rescue:
    - name: clean up after failure
      file:
        path: /etc/swift/{{ item }}
        state: absent
      with_items:
        - [ account.builder, container.builder, object.builder, account.ring.gz, container.ring.gz, object.ring.gz ]
    - name: fail on error during ring creation
      fail:
        msg: swift ring creation failed, check the ansible log
