---
- name: install swift storage components
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - rsync
    - swift
    - swift-account
    - swift-container
    - swift-object

- name: create rsyncd config
  template:
    src: rsyncd.conf.j2
    dest: /etc/rsyncd.conf
    owner: root
    group: root
    mode: 0644

- name: enable rsyncd
  lineinfile:
    dest: /etc/default/rsync
    regexp: ^#\s*RSYNC_ENABLE=
    line: RSYNC_ENABLE=true
  notify: restart rsync

- meta: flush_handlers

- name: enable / start rsync service
  service:
    name: rsync
    enabled: '{{ rsync_enabled | default("yes") }}'
    state: '{{ rsync_state | default("started") }}'
