---
- name: install swift controller components
  apt:
    state: present
    name: '{{ item }}'
  with_items:
    - swift
    - swift-proxy
    - python-swiftclient
    - python-keystoneclient
    - python-keystonemiddleware

- name: create swift config directory
  file:
    state: directory
    path: /etc/swift
    owner: root
    group: swift
    mode: 0755

- name: retrieve rings/builders/swift.conf from one of the storage nodes
  slurp:
    src: /etc/swift/{{ item }}
  delegate_to: "{{ groups['storage-nodes'] | random  }}"
  register: rings
  with_items:
    - '{{ swift_files }}'

- name: store ring/builder/swift.conf files
  copy:
    content: '{{ item.content }}'
    dest: /etc/swift/{{ item.source | basename }}.b64
    owner: root
    group: swift
    mode: 0644
  no_log: true
  with_items:
    - "{{ rings.results }}"
  notify: decode swift files

- name: swift proxy-server configuration
  ini_file:
    dest: /etc/swift/proxy-server.conf
    owner: root
    group: swift
    mode: 0644
    section: '{{ item.section }}'
    option: '{{ item.option|default(omit) }}'
    value: '{{ item.value|default(omit) }}'
  no_log: true
  with_items:
    - '{{ swift_proxy_config_base + swift_proxy_config|default([]) }}'
  notify: restart swift-proxy

- meta: flush_handlers

- name: enable / start swift-proxy service
  service:
    name: swift-proxy
    enabled: '{{ swift_proxy_enabled | default("yes") }}'
    state: '{{ swift_proxy_state | default("started") }}'
