---
swift_account_listen: 127.0.0.1
swift_container_listen: 127.0.0.1
swift_object_listen: 127.0.0.1
swift_rsync_listen: 127.0.0.1
swift_root: /srv/node
swift_partition_exponent: 10
swift_replicas: '{{ swift_disks|length }}'
swift_rebalance_limit: 1

swift_config_base:
  - { section: 'swift-hash', option: 'swift_hash_path_suffix', value: '{{ swift_hash_path_suffix }}' }
  - { section: 'swift-hash', option: 'swift_hash_path_prefix', value: '{{ swift_hash_path_prefix }}' }
  - { section: 'storage-policy:0', option: 'name', value: 'Policy-0' }
  - { section: 'storage-policy:0', option: 'default', value: 'yes' }
  - { section: 'swift-constraints', option: '', value: '' }

swift_account_config_base:
  - { section: 'DEFAULT', option: 'bind_ip', value: '{{ swift_account_listen  }}' }
  - { section: 'DEFAULT', option: 'bind_port', value: '6002' }
  - { section: 'DEFAULT', option: 'user', value: 'swift' }
  - { section: 'DEFAULT', option: 'swift_dir', value: '/etc/swift' }
  - { section: 'DEFAULT', option: 'devices', value: '{{ swift_root }}' }
  - { section: 'DEFAULT', option: 'mount_check', value: 'true' }
  - { section: 'pipeline:main', option: 'pipeline', value: 'healthcheck recon account-server' }
  - { section: 'app:account-server', option: 'use', value: 'egg:swift#account' }
  - { section: 'filter:healthcheck', option: 'use', value: 'egg:swift#healthcheck' }
  - { section: 'filter:recon', option: 'use', value: 'egg:swift#recon' }
  - { section: 'filter:recon', option: 'recon_cache_path', value: '/var/cache/swift' }
  - { section: 'account-replicator', option: 'None', value: 'None' }
  - { section: 'account-auditor', option: 'None', value: 'None' }
  - { section: 'account-reaper', option: 'None', value: 'None' }
  - { section: 'filter:xprofile', option: 'use', value: 'egg:swift#xprofile' }
swift_container_config_base:
  - { section: 'DEFAULT', option: 'bind_ip', value: '{{ swift_container_listen  }}' }
  - { section: 'DEFAULT', option: 'bind_port', value: '6001' }
  - { section: 'DEFAULT', option: 'user', value: 'swift' }
  - { section: 'DEFAULT', option: 'swift_dir', value: '/etc/swift' }
  - { section: 'DEFAULT', option: 'devices', value: '{{ swift_root }}' }
  - { section: 'DEFAULT', option: 'mount_check', value: 'true' }
  - { section: 'pipeline:main', option: 'pipeline', value: 'healthcheck recon container-server' }
  - { section: 'app:container-server', option: 'use', value: 'egg:swift#container' }
  - { section: 'filter:healthcheck', option: 'use', value: 'egg:swift#healthcheck' }
  - { section: 'filter:recon', option: 'use', value: 'egg:swift#recon' }
  - { section: 'filter:recon', option: 'recon_cache_path', value: '/var/cache/swift' }
  - { section: 'container-replicator', option: 'None', value: 'None' }
  - { section: 'container-auditor', option: 'None', value: 'None' }
  - { section: 'container-updater', option: 'None', value: 'None' }
  - { section: 'container-sync', option: 'None', value: 'None' }
  - { section: 'filter:xprofile', option: 'use', value: 'egg:swift#xprofile' }
swift_object_config_base:
  - { section: 'DEFAULT', option: 'bind_ip', value: '{{ swift_object_listen  }}' }
  - { section: 'DEFAULT', option: 'bind_port', value: '6000' }
  - { section: 'DEFAULT', option: 'user', value: 'swift' }
  - { section: 'DEFAULT', option: 'swift_dir', value: '/etc/swift' }
  - { section: 'DEFAULT', option: 'devices', value: '{{ swift_root }}' }
  - { section: 'DEFAULT', option: 'mount_check', value: 'true' }
  - { section: 'pipeline:main', option: 'pipeline', value: 'healthcheck recon object-server' }
  - { section: 'app:object-server', option: 'use', value: 'egg:swift#object' }
  - { section: 'filter:healthcheck', option: 'use', value: 'egg:swift#healthcheck' }
  - { section: 'filter:recon', option: 'use', value: 'egg:swift#recon' }
  - { section: 'filter:recon', option: 'recon_cache_path', value: '/var/cache/swift' }
  - { section: 'filter:recon', option: 'recon_lock_path', value: '/var/lock' }
  - { section: 'object-replicator', option: 'None', value: 'None' }
  - { section: 'object-auditor', option: 'None', value: 'None' }
  - { section: 'object-reconstructor', option: 'None', value: 'None' }
  - { section: 'object-updater', option: 'None', value: 'None' }
  - { section: 'filter:xprofile', option: 'use', value: 'egg:swift#xprofile' }

swift_files:
  - account.builder
  - container.builder
  - object.builder
  - account.ring.gz
  - container.ring.gz
  - object.ring.gz
  - swift.conf
  - .rings_build

